# default document denoted by the name "DEFAULT"
name: "DEFAULT"
repetitions: 5
iterations: 4000
path: "/work/scratch/qd34dado/generalTsallisv2"


params:
    batch_size: 400
    learning_rate: 0.01
    tau: 0.01
    q: 2.0
    k: 1.0


---
# 1. experiment
name: "tau"
list:
    tau: [0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09]

#---
# 2. experiment
#name: "memory_batch_pair"
#grid:
#    memory_size: [20000, 200000, 2000000]
#    batch_size: [300, 500]
